# Site settings
baseurl: ''
url: 'https://www.hintdesk.com'
title: 'Tri Nguyen'
description: 'Hintdesk is the personal blog of Tri Nguyen'
author: 'Tri Nguyen'

# Build settings
permalink: /:year/:month/:day/:title/
plugins: [ jekyll-sitemap, jekyll-feed, jekyll-seo-tag ]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

# Stylesheets
stylesheets:
  - '/css/stylesheet.css'
  - '/css/syntax.css'

# Google Analytics
google-analytics:
  enabled: false
  id: ''

# The primary language used by the website
language: 'en'

# Favicon and icons for iOS, Android
# These should ideally be located in the root directory
apple-touch-icon: '/apple-touch-icon.png'
favicon-32: '/favicon-32x32.png'
favicon-16: '/favicon-16x16.png'
site-manifest: '/site.webmanifest'

# The logo motif
logo-motif:
  enabled: false
  src: '/assets/img/logo.png'
  width: '128'
  height: '128'

# The logo title
logo-title:
  enabled: false

# Header menu
header-menu:
- { name: 'Home', url: '/' }
- { name: 'About', url: '/about' }
- { name: 'Articles', url: '/articles' }

# Footer menu
footer-menu:
- { name: 'Home', url: '/' }
- { name: 'About', url: '/about' }
- { name: 'Articles', url: '/articles' }
- { name: 'RSS', url: '/feed.xml' }

# Homepage
homepage:
  # header-text: 'Hintdesk is the personal website of Tri Nguyen'
  intro-text: '<a href="/about">Tri Nguyen</a> is a full stack developer, software engineer, software 
              architect, project leader working in Bayern, Germany. 
              I just write some notes for me here. 
              No big deal. You can read more in the <a href="/articles">archives</a>.'
  #intro-image: 'intro.png'
  latest-articles-enabled: true
  latest-articles-title-text: 'Latest Articles'
  latest-articles-link-enabled: true
  latest-articles-link-url: '/articles'
  latest-articles-link-text: 'View all articles'

# Articles
articles:
  header-text: 'All Articles'
  excerpt-enabled: true
  read-more-enabled: true
  read-more-text: 'Read more'

# Post Icons
icons:
  enabled: true

# Related posts (only works if you use tags)
related-posts:
  enabled: true
  header-text: 'More articles like this...'
  limit: 3
  no-related-articles-text: 'We couldn''t find any similar articles!'

# Written on (post info displayed underneath the H1)
written-on:
  enabled: true
  by-text: 'By'
  on-text: 'on'
